### ISSUE TITLE
serialize configuration

### ISSUE THREAD

**Issue by danshapir** [jherdman/ember-cli-trackjs#3] opened 2015-03-27 22:48 UTC
Hey,

How can I setup the serialize config? I've tried through the ENV, but nothing worked..

**Comment by jherdman** [comment] 2015-03-28 15:13
Wow, confirmed! This is pretty wacky. I'm looking into the problem now.

**Comment by jherdman** [comment] 2015-03-28 15:22
I think your safest bet as a workaround until I can figure out the root cause of the problem is to do the following in an initializer:

```javascript
// in your initializer...
initialize: function() {
  window._trackJs.serialize = function(what) {
    // custom logic, etc.
    return what.toString();
  };
}
```

**Comment by danshapir** [comment] 2015-03-28 16:08
Hey,

The root of the caouse is that JSON.stringify ignores functions. You should use something else for that.

I'm checking the workaround you've suggested, but since the code must run before the trackJs script loads to the page, I'm pretty sure it won't work. I'll check and update.

**Comment by danshapir** [comment] 2015-03-28 16:35
Hey,

I've done some research, here is the solution.
The token has to be written the way you've done it, but all the other configuration options do not. You should add them in the initializer you've created for the package, should be really easy to implement:

Call trackJs.configure({}) after {Track:js} has been initialized

The {} being the configuration from the file!

**Comment by jherdman** [comment] 2015-03-29 21:47
Seems like a good plan, I appreciate the research you've done on this. I'll whip up an official fix shortly.

**Comment by jherdman** [comment] 2015-03-31 13:23
TIL the environment is serialized into JSON and stored in a meta tag:

```html
    <base href="/" />
<meta name="dummy/config/environment" content="%7B%22modulePrefix%22%3A%22dummy%22%2C%22environment%22%3A%22development%22%2C%22baseURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%7D%2C%22APP%22%3A%7B%22name%22%3A%22ember-cli-trackjs%22%2C%22version%22%3A%220.1.3.690abc0c%22%7D%2C%22trackJs%22%3A%7B%22addon%22%3A%7B%22url%22%3A%22/fake-trackjs.js%22%7D%2C%22config%22%3A%7B%22token%22%3A%22fake-token%22%7D%7D%2C%22contentSecurityPolicyHeader%22%3A%22Content-Security-Policy-Report-Only%22%2C%22contentSecurityPolicy%22%3A%7B%22default-src%22%3A%22%27none%27%22%2C%22script-src%22%3A%22%27self%27%20%27unsafe-eval%27%22%2C%22font-src%22%3A%22%27self%27%22%2C%22connect-src%22%3A%22%27self%27%22%2C%22img-src%22%3A%22%27self%27%22%2C%22style-src%22%3A%22%27self%27%22%2C%22media-src%22%3A%22%27self%27%22%7D%2C%22exportApplicationGlobal%22%3Atrue%7D" />
<script src="/ember-cli-live-reload.js" type="text/javascript"></script>
<script type="text/javascript" id="trackjs-configuration">window._trackJs = { token: "fake-token" };</script>
<script type="text/javascript" id="trackjs-boilerplate" src="/fake-trackjs.js" crossorigin="anonymous"></script>
```

Fun, eh? I think this means we *have to* either use a workaround, or introduce a new configuration mechanism. I'm going to chew on this a bit more.

**Comment by jherdman** [comment] 2015-04-03 22:18
Apologies for the delay in resolving this. If you have a chance this weekend, would you mind looking over #9? I'm circling a solution, but it's unfortunately going to be a breaking change. I'm hoping to get some feedback as I test out my solution.

**Comment by danshapir** [comment] 2015-04-04 11:17
Sure, ill try it today.

**Closed** 2015-07-06 14:54 UTC
